app:
    resource: '@AppBundle/Controller/'
    type: annotation
logout:
    path: /logout
login:
    path:     /{_locale}/login
    defaults: { _controller: AppBundle:Security:login }
    requirements:
        _locale: '%app.locales%'

app_api_v1:
    resource: '@AppBundle/Controller/Api/'
    type: annotation
